version: '3.2'
services:
  python3:
    restart: always
    build: .
    container_name: 'practice-transformer'
    working_dir: '/root/'
    tty: true
    volumes:
      - type: bind
        source: .
        target: /root/practice-transformer
